name: "Frogbot Repository Scan"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["main"]
    steps:
      # - uses: jfrog/setup-jfrog-cli@v4
      #   env:
      #     JF_URL: ${{ vars.JF_URL }}
      #   with:
      #     oidc-provider-name: nitin-jfrog-github-oidc 
      - uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: nitin-jfrog-github-oidc
        env:
          ACTIONS_STEP_DEBUG: true
          # [Mandatory]
          # JFrog platform URL
          JF_URL: ${{ vars.JF_URL }}

          # [Optional, default: "TRUE"]
          # Fails the Frogbot task if any security issue is found.
          JF_FAIL: "FALSE"
